### ISSUE TITLE
Scene Viewer cannot set mode

### ISSUE THREAD

**Issue by patrickbusser** [google-ar/sceneform-android-sdk#1027]
Im trying to launch Scene Viewer using an explicit intent to the Google Search package, but I don't manage to set the mode of the Scene Viewer and imo the documentation is not very clear on how to put the supported intent parameters: https://developers.google.com/ar/develop/java/scene-viewer#supported_intent_parameters

`Intent sceneViewerIntent = new Intent(Intent.ACTION_VIEW);
        sceneViewerIntent.setData(Uri.parse("https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF/Avocado.gltf"));
        sceneViewerIntent.setPackage("com.google.android.googlequicksearchbox");
        sceneViewerIntent.putExtra("mode","3d_only");
        startActivity(sceneViewerIntent);`

When I launch the app, it opens in the scene viewer intent, but in 3d_preferred mode. Does anyone know how to solve this issue?

**Comment by tpsiaki** [comment]
Hi @patrickbusser - thanks for the report.  The issue you're running into is because the mode needs to be added to the intent Uri, rather than added as an extra.

In order for the sample you shared to work you would need to add `?mode=3d_only` to the end of the gltf uri.

Also of note, just today we updated the intent scheme for Scene Viewer to allow better disambiguation between the parameters passed to the intent, and any potential parameters passed to a Uri in the intent.  The ideal way to launch Scene Viewer for the content you're target is this:

```
Intent sceneViewerIntent = new Intent(Intent.ACTION_VIEW);
Uri intentUri =
    Uri.parse("https://arvr.google.com/scene-viewer/1.0").buildUpon()
    .appendQueryParameter("file", "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF/Avocado.gltf")
    .appendQueryParameter("mode", "3d_only").build();
sceneViewerIntent.setData(intentUri);
sceneViewerIntent.setPackage("com.google.android.googlequicksearchbox");
sceneViewerIntent.putExtra("mode", "3d_only");
startActivity(sceneViewerIntent);
```

**Comment by patrickbusser** [comment]
Thank you for the quick reply, works like a charm!
