### ISSUE TITLE
Change Texture of SelectionVisualizer for Selected TransformableNodes

### ISSUE THREAD

**Issue by malulleybovo** [google-ar/sceneform-android-sdk#106]
Is there a way in the current version to change the texture of (or even remove) the white circle that identifies the selected object? FootprintSelectionVisualizer's setFootprintRenderable and removeSelectionVisual methods seem to allow that but I could not find a way to get the object reference from ArFragment. Is it possible?

**Comment by dsternfeld7** [comment]
You can achieve this by instantiating your own TransformationSystem instead of using the one provided by ArFragment. The TransformationSystem constructor takes a SelectionVisualizer, so you can create your own FootprintSelectionVisualizer, or create your own implementation of SelectionVisualizer.

```
    transformationSystem =
        new TransformationSystem(getResources().getDisplayMetrics(), selectionVisualizer);
```

Make sure you pass touch events into your new TransformationSystem using [setOnPeekTouchListener](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/Scene.html#setOnPeekTouchListener(com.google.ar.sceneform.Scene.OnPeekTouchListener))

`    transformationSystem.getGestureDetector().onTouch(hitTestResult, motionEvent);`

We will look into allowing you to change the selection visualizer more directly for a future release.

**Comment by malulleybovo** [comment]
Thank you for the reply! However, does making a new TransformationSystem not mean that the gesture detection will not be as smooth as in the TransformationSystem embedded into ArFragment?

I tried this workaround (create a new TransformationSystem, setOnPeekTouchListener, and pass the custom TransformationSystem when making TransformableNodes) and noticed that:
1) the circle for selected nodes is not on by default.
2) Since setOnPeekTouchListener seemed to disable calls to ArFragment's OnTapArPlaneListener, it lead me to handle plane interaction (place nodes) in the Scene listeners.
3) Performing the above without extra checks (for MotionEvent type, HitTestResult.getNode(), etc.) resulted in the rotation gesture also placing a Node when the two fingers don't touch the display at the same time (i.e.: it places then rotates even though the default TranformationSystem seems to handle this effectively).

Therefore, at least from my experimentation, it seems this workaround will disable other wanted features in order to gain control over the selection visualizer. Is this truly the case or is there a step I am missing to accomplish this without side effects?

**Comment by dsternfeld7** [comment]
For problem 2 & 3, call the fragment's onPeekTouch from within your peek touch listener. From the docs for BaseArFragment:

> If setOnPeekTouchListener(Scene.OnPeekTouchListener) is set, then onPeekTouch(HitTestResult, MotionEvent) must be called manually to ensure that the TransformationSystem and setOnTapArPlaneListener(OnTapArPlaneListener) work.

I'm not as sure what was going on with problem 1. Are you calling TransformableNode.select() after creating the new Node?

**Comment by dsternfeld7** [comment]
An additional note, TapArPlaneListener is implemented using an android [GestureDetector](https://developer.android.com/reference/android/view/GestureDetector). This will determine when a tap occurs by looking at a sequence of ACTION_DOWN and then ACTION_UP within a slop threshold. I suspect that problem 3 would happen if you placed nodes on ACTION_DOWN, since that gesture would conflict with the two finger twist gesture.

**Comment by malulleybovo** [comment]
Calling OnPeekTouch solved the issue! Regarding your question above, I do call select() after creating the node. The selection circle won't show but the node is indeed selected.

**Comment by dsternfeld7** [comment]
I'm glad that helped!

Are you using FootprintSelectionVisualizer or creating your own? If you create your own, you can verify that SelectionVisualizer.applySelectionVisual is getting called when the node is selected.

If you share your code, I can try to help debug the issue.

**Comment by malulleybovo** [comment]
My goal with this was to verify possibilities. I used the hellosceneform sample project and added the following lines onCreate after initializing arFragment:
```java
FootprintSelectionVisualizer selectionVisualizer = new FootprintSelectionVisualizer();
TransformationSystem transformationSystem = new TransformationSystem(getResources().getDisplayMetrics(), selectionVisualizer);
arFragment.getArSceneView().getScene().setOnPeekTouchListener((hitTestResult, motionEvent) -> {
    arFragment.onPeekTouch(hitTestResult, motionEvent);
    transformationSystem.getGestureDetector().onTouch(hitTestResult, motionEvent);
});
```

Then when placing instances of our friend, Andy, I pass my custom transformationSystem instead of arFragment.getTransformationSystem(). Doing just this resulted in same expected functionality but without the white circle being drawn in space to help visualize the selection. I have not tried setting it so some custom renderable. Regardless, it seems to me like the renderable is null by default unless the developers would say otherwise.

**Comment by dsternfeld7** [comment]
Thanks! Ya, you need to call [setFootprintRenderable](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/FootprintSelectionVisualizer.html#setFootprintRenderable(com.google.ar.sceneform.rendering.ModelRenderable)) on the visualizer to tell the visualizer what renderable to use as the footprint.
