### ISSUE TITLE
Possible to remove support library dependency?

### ISSUE THREAD

**Issue by PaulTVungle** [google-ar/sceneform-android-sdk#118]
I'm using the APK analyser on my app and it reports 15300 or so defined methods, 9900 or which are from android.support.

I see that ArFragment uses the support.v4 version of Fragment, but am not sure what else is required from the support library.

Is android.support genuinely needed or could it be evicted and save the best part of 10000 methods from my (rather method-count-sensitive) executable?  I'm sorry to say those extra methods might prevent us from shipping a product :-(

(Unfortunately there are still some edge cases where multidex is not applicable.)

Thanks

**Comment by malik-at-work** [comment]
There are a variety of options here.  I'll discuss with the team and make a recommendation.

**Comment by malik-at-work** [comment]
One way this might be possible is to use ArSceneView directly and not use ux.BaseArFragment. That inherits from Fragment which is in the support library.  BaseArFragment isn't strictly needed since it composes functionality added by other classes.  Mainly it's using ArSceneView to display objects in AR and communicate with ArCore.

  TransformationSystem and GestureDetector from the ux package are used to detect touch and manipulate objects.  You can instantiate these yourself in a new class instead of using BaseArFragment.  The selection visualizer issue https://github.com/google-ar/sceneform-android-sdk/issues/106 has some information about how to do that.  If you have some other way for users to manipulate objects you will not need these at all.

**Comment by PaulTVungle** [comment]
Yes, sounds like a plan.  I don't need the TransformationSystem and GestureDetector as we are just using the node click callback.

It's a shame to have to do the permission check and helper app tests manually, but I don't think that would take too long to sort out.  Will give it a go, thanks.
