### ISSUE TITLE
Precision of getStartSeconds

### ISSUE THREAD

**Issue by PaulTVungle** [google-ar/sceneform-android-sdk#127]
Could you consider promoting the returned value of FrameTime.getStartSeconds to a double precision value instead of a float?

I quite often write code that uses the current time:

    position.x = (frameTime.getStartSeconds() - startSeconds) * distance;
    setLocalPosition(position);

My experience is that you need better than millisecond precision for animations like this to appear smooth, and with a float value that has maybe seven digits of accuracy on a timer that seems to have started at device boot, the resolution needed will be exhausted after only a few minutes have elapsed.

Thanks

**Comment by malik-at-work** [comment]
Thanks for the request!

**Comment by claywilkinson** [comment]
This is fixed in 1.5 by using [`FrameTime.getDeltaTime()`](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/FrameTime#getDeltaTime(java.util.concurrent.TimeUnit))  and [`FrameTime.getStartTime()`](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/FrameTime#getStartTime(java.util.concurrent.TimeUnit))
