### ISSUE TITLE
How to implement Image tracking in ARCore like ARKit 2.0 ?

### ISSUE THREAD

**Issue by mistrydarshan99** [google-ar/sceneform-android-sdk#145]
Hello,

I have seen image tracking feature in ARKit 2.0 but this feature is not found in ARCore. Is it possible to implement image tracking in ARCore? 

Image tracking iOS: https://twitter.com/azamsharp/status/1004147396182511617

**Comment by joreilly** [comment]
@mistrydarshan99 is this what you mean https://developers.google.com/ar/develop/c/augmented-images/ ?

**Comment by mistrydarshan99** [comment]
@joreilly I am talking about image tracking. In iOS as image move node also moves with an image as seen in reference url but in android ARCore I didn't found like ios image tracking. You can also search ARKit 2.0 image tracking so you have got a better idea and got a difference between ios ARKit and android ARCore.

**Comment by dsternfeld7** [comment]
The [augmented images](https://developers.google.com/ar/develop/c/augmented-images/) feature in ArCore is the most similar functionality in android. However, tracking a moving image is not supported.

Since this question doesn't pertain specifically to Sceneform, I'm closing this issue. Please feel welcome to post an issue in the [ArCore Android SDK GitHub](https://github.com/google-ar/sceneform-android-sdk) requesting this feature.
