### ISSUE TITLE
how to set opacity for makeTransparentWithTexture material

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#196]
Hello.

When I create a material with makeTransparentWithColor, I can set the opacity with the alpha parameter of the color. Is there a way to set the opacity of a material created with makeTransparentWithTexture during runtime? The renderable is a ShapeFactory Cube.

Thanks,
Michael

**Comment by claywilkinson** [comment]
Unfortunately, there is no way to affect the opacity of that material.  The materialFactory generated materials are intended more for simple materials or placeholders during development.

You can create a custom material for your model that you could set a base texture and then pass in a parameter to affect the final color.

I don't have a sample of that handy, but let me know if you have questions.

**Comment by dsternfeld7** [comment]
To clarify, when using makeTransparentWithTexture, the transparency of the material comes from the alpha channel of the texture. My understanding is that what you want is to control the transparency uniformly for the object with a float from 0-1 for use with a slider instead. To do this, you can write a custom material that has a scale factor multiplied against the alpha from the texture.

When writing a custom material, you can add a float parameter called alphaFactor and do this in the fragment block of the material:

```
material.baseColor = texture(materialParams_texture, getUV0());
material.baseColor.a *= materialParams.alphaFactor;
```

In regards to creating a custom material at runtime, there is currently no way to load a material outside of an .sfb. However, changing this is on our radar. That leaves two options, you can create a .sfb and use that instead of the ShapeFactory, OR you can create a dummy .sfb, load that as a Renderable, and then do renderable.getMaterial() to get the material and pass it into the ShapeFactory.

Once you have the custom material, you could change the parameter you created at runtime by doing material.setFloat("alphaFactor", alpha);

**Comment by michaelvogt** [comment]
Thank you for clarification. 

Glad to hear (read) that loading a material outside of an .sfb is on your radar. Can we keep this ticket open as a feature request?

**Comment by dsternfeld7** [comment]
No problem! We currently are tracking this feature request through issue [https://github.com/google-ar/sceneform-android-sdk/issues/157](https://github.com/google-ar/sceneform-android-sdk/issues/157). We prefer not to keep duplicate issues open, and to have separate issues open for things instead of having one large issue that encapsulates multiple things.

**Comment by romainguy** [comment]
The alpha value of `baseColor` only applies to diffuse lighting. Specular highlights are by definition reflected light and are therefore unaffected by the transparency of the surface. It is however useful to be able to affect both diffuse and specular lighting together for fade effects. This will require a new feature in custom materials.

**Comment by dsternfeld7** [comment]
To add to that, in the meantime you can fade an object out entirely by using the unlit shading model in the custom material.

**Comment by michaelvogt** [comment]
👍

**Comment by romainguy** [comment]
I implemented the new feature internally. It's a new blending mode called "fade".

**Comment by dsternfeld7** [comment]
In the material block, try adding `"blending" : "transparent"`. There is more information about the different blend modes on [this](https://developers.google.com/ar/develop/java/sceneform/custom-material) page.

**Comment by michaelvogt** [comment]
Yes, works - of course.
Sorry for not finding this myself...
