### ISSUE TITLE
[question] apply texture on 3d cube generated by ShapeFactory

### ISSUE THREAD

**Issue by ernieboogie** [google-ar/sceneform-android-sdk#199]
Hi guys, I currently working on android app about AR gallery

and from issue https://github.com/google-ar/sceneform-android-sdk/issues/194 
i could make 3d cube on my surfaceView.

and from the code posted on issue https://github.com/google-ar/sceneform-android-sdk/issues/197
i could apply textrue on 3d cube that i generated.
(my code is completely same with that code)

i used artwork image as texture image, but the problem is all the 6 sides of cube is textured by 
that image.
What i want to do is just texturing just 1 side(front side, other sides just white).

is it possible texturing each side of cube generated shapefactory?

i'm totally newbie about 3D rendering or graphics..
i did some search about modelrenderable, material , submeshes..
but my cube renderable's submesh count is 1 so i'm stuck here.

**Comment by Berenice2018** [comment]
@ernieboogie I think this texture behaviour is expected and normal. It would be the same when using a primitive shape in Unity3D. We would have to use a custom model instead of the cube instantiated with ShapeFactoy. The custom cube must have different UV mapping. So that just one side of the cube is textured. UV mapping defines how faces of your cube get textured. 

Another workaround could be the following one: create 5-6 planes with ShapeFactory, position them so that they look like a cube, and texture just the front plane. I do not know whether it is necessary to group the planes to a parent node for further translation adjustments. This could become a bit complicated in Sceneform and result in unexpected behaviour, I guess. 

Good luck with your project!
