### ISSUE TITLE
How to set Node dimensions in meters?

### ISSUE THREAD

**Issue by itanbp** [google-ar/sceneform-android-sdk#210]
Hi,
I'm looking for a way to set the Node's dimensions in meters.

```
Node model = new Node();
model.setParent(parentNode);
model.setRenderable(macaronRenderable);
// something like this - the model's X axis dimension will be 60 centimeters
model.setDimensions(new Vector3(0.6f, 0.1f, 0.3f));
// scale the Node instead of setting the dimensions 
model.setLocalScale(new Vector3(0.6f, 0.1f, 0.3f));
```
Thanks!

**Comment by gstanlo** [comment]
You can presently access the collision bounds of a renderable which might be suitable. You can then determine the proper scale factor by dividing the target scale by collision bounds size. 

Can you describe the behavior you're trying to achieve by scaling a dimension to a specific size? An irregularly shaped object might not scale well like this.

**Comment by gstanlo** [comment]
Beware that this code scales the *bounds* of the object. It looks like the height of the cherry + its stem is the same as the height of the box, doesn't it? In this case, the collision bounds extend to the top of the cherry, but I'm assuming what you want is for the body of the cherry to be roughly the size of the box.

There isn't a simple way to achieve that in code right now. One option may be to try to accept models with specified units (meters, centimeters, inches, etc) and do the conversion when necessary, so that all the models can be authored to their real world size.

**Comment by itanbp** [comment]
> It looks like the height of the cherry + its stem is the same as the height of the box, doesn't it?

Well, I looked from several positions and perspectives, and the cherry + stem height **doesn't look** like the box height.
But I found my mistake, I changed the cube's origin `Renderable renderable = ShapeFactory.makeCube(new Vector3(0.3f, wantedRealHeight, 0.3f), new Vector3(0.0f, 0.0f, 0.0f), material);` to `new Vector3(0.0f, wantedRealHeight/2, 0.0f)`, and now the models look like they have the same height.

Thanks!
