### ISSUE TITLE
SceneForm OpenGLES 3.1 requires on android emulator

### ISSUE THREAD

**Issue by flyingdevil84210** [google-ar/sceneform-android-sdk#220]
The graphic card of my computer can run   OpenGl 4.3 ![gpu caps viewer](https://user-images.githubusercontent.com/41890887/43390066-99ff8868-93ed-11e8-90e5-249db17b8db3.png)
and when i try to run the "HelloSceneForm" application  in the android emulator the error message "HelloSceneForm requires OpengleEs 3.1 or later" is send.

 ![android emulator](https://user-images.githubusercontent.com/41890887/43390068-9a1e5cc0-93ed-11e8-9875-2ac465975c99.png).

 I already have set "Renderer Maximum  (up to OpenGL ES to 3.1)   on the advanced settings of the emulator and set "GLESDynamicVersion" to "on" in the "AdvancedFeatures.ini" file but the issu is persisting. 
![extended controls](https://user-images.githubusercontent.com/41890887/43390070-9a42bb7e-93ed-11e8-9906-db82d63aef75.png)

Does anyone knows what can i do to solve this issu?
Thanks by advance.

**Comment by malik-at-work** [comment]
There is discussion on this issue at https://github.com/google-ar/sceneform-android-sdk/issues/4

**Comment by romainguy** [comment]
OpenGL on desktop is different than OpenGL ES. OpenGL 4.3 != OpenGL ES 3.1. The emulator should be able to run OpenGL ES 3.1 applications on Linux though. Note however that the next version of Sceneform will require OpenGL ES 3.0 only which should fix your problem.

**Comment by flyingdevil84210** [comment]
@romainguy . Thank you for your  fast reply.
Do you know the release date of the next version?

**Comment by jwmcglynn** [comment]
Hey @flyingdevil84210, Sceneform 1.4 is now available which supports OpenGL ES 3.0.  Can you give the new version a try?

**Comment by jwmcglynn** [comment]
I'm going to close this issue, please reopen or create a new issue if you're still having issues after updating to Sceneform 1.4.

**Comment by flyingdevil84210** [comment]
Hi,

I am sorry for the late reply. I confirm that everything is running now on the emulator with 
both updates ( Sceneform 1.4 and ARCore SDK 1.4).
Thank you very much for you great job.

Regards.

Eric Vicario

----- Mail original -----
De: "Jeff McGlynn" <notifications@github.com>
À: "google-ar/sceneform-android-sdk" <sceneform-android-sdk@noreply.github.com>
Cc: "flyingdevil84210" <eric.vicario@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Vendredi 3 Août 2018 02:17:16
Objet: Re: [google-ar/sceneform-android-sdk] SceneForm OpenGLES 3.1 requires on android emulator (#220)



Closed #220 .

**Comment by ritesh-goel** [comment]
Hi,

I checked the supported version on my ubuntu as per `glxinfo | grep OpenGL` command

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

Seems like OpenGL ES 3.2 is supported. In emulator, i logged the version of OpenGL ES which turned out to be 2.0

How do i upgrade it?
