### ISSUE TITLE
Field of View Discrepancy

### ISSUE THREAD

**Issue by aayc** [google-ar/sceneform-android-sdk#225]
Hi,

For some reason, when I use arFragment.getArSceneView().getArFrame().acquireCameraImage(), which returns an image, the image is different in field of view than the fragment's display.

In other words, I thought that what I see through the AR fragment is what is captured via acquireCameraImage, but it looks like the the acquired image encompasses a wider field of view.

Here's a screenshot:  The bigger image is what is seen through the AR fragment.  The smaller image is an image view that shows the image captured via acquireCameraImage - notice how it shows much more of the screen surrounding the picture of the man.
![screenshot_20180731-083750](https://user-images.githubusercontent.com/16508619/43461224-efcfb516-94a0-11e8-90cf-3ddfa83bd511.png)

I'd like to make these match in some way (so that I can take an image, process it, and apply it to what the user sees).  Is there some kind of transformation I can make on the acquired image to make it match what's seen in the fragment?

Thanks!

**Comment by gstanlo** [comment]
The image from acquireCameraImage is indeed going to be a different resolution than the one in an ArFragment.  In the ARCore computer vision sample, the texture coordinates get stretched, effectively cropping the image to fit the proper aspect ratio. See [this ](https://github.com/google-ar/arcore-android-sdk/blob/e00f55162fa27ae03b57599f7b84e29098992456/samples/computervision_java/app/src/main/java/com/google/ar/core/examples/java/computervision/CpuImageRenderer.java#L284)method.

The ARCore version uses GLES to render the image however. How would you like to present the data from acquireCameraImage?

**Comment by aayc** [comment]
Ah okay, my solution was to crop the acquired camera image to 640x360 instead of 640x480 to match the 1920x1080 aspect ratio.  Thanks @gstanlo for your help!

**Comment by DrPaulT** [comment]
Rather than open a new issue, I'd like to ask a question here about the frames returned by acquireCameraImage.

I am also taking frames from the camera stream to use for processing, and am making some assumptions about the frame size and type.  I am ok making these assumptions or should I do some further (time-consuming) processing eg. checking size and scaling?

* acquireCameraImage always returns frames in landscape mode at 640x480.
* Sensors are always 4x3, so this will always be the whole frame, there will be no aspect distortion.
* The background projected onto the scene view is a central crop of this frame in landscape mode with the left and right edges being common to both rasters.
* Frames will always be three-channel YUV_***_888 of some sort.

Would be great to know if this is the case for all supported ARCore devices now.  I appreciate there's unlikely to be any information available for unreleased devices, but is the general plan to stick to 640x480 for the foreseeable future?

Thanks.
