### ISSUE TITLE
What is the purpose of bound_relative_root attribute in the SFA file?

### ISSUE THREAD

**Issue by itanbp** [google-ar/sceneform-android-sdk#233]
Hi,
In the SFA file, I see an attribute named `bound_relative_root` with default values:
```
{
   bound_relative_root: {
      x: 0.5,
      y: 0,
      z: 0.5,
   },
   materials: [
```

Didn't find an explanation for this attribute's purpose in the [documentation](https://developers.google.com/ar/develop/java/sceneform/sfa).

Thanks!

**Comment by tpsiaki** [comment]
Hi @itanbp - the bound_relative_root attribute is a bug that slipped through in this release.  The value here is ignored and not used for anything.

Note that this bug is related to the new recentering behavior introduced for the model.recenter attribute in the [SFA format](https://developers.google.com/ar/develop/java/sceneform/sfa).

You can now adjust the local origin of your model automatically to the bottom of the model with recenter:"root" (this would be useful if you want to make sure your object appears on the floor.  You can also position the local origin in a specific location related to the axis-aligned-bounding-box of the asset's geometry using an {x: y: z:} value in model.recenter.

To reiterate though, bound_relative_root is ignored and doesn't do anything.  In the next release it will no longer appear in SFA files when you import a new model.

**Comment by itanbp** [comment]
@tpsiaki  thanks!
