### ISSUE TITLE
SolarSystem sample not rendering properly

### ISSUE THREAD

**Issue by ritesh-goel** [google-ar/sceneform-android-sdk#262]
Hi,

When i run the sample solar system app on emulator, it distorts as shown below.
![screenshot_1534393314](https://user-images.githubusercontent.com/4611445/44223955-bb129380-a1a6-11e8-992c-3b945e0b277f.png)
But when i move camera around, the scene looks fine, only when the model is in current frame, the view distorts.
Is this an issue with the code or the emulator/system?

**Comment by jwmcglynn** [comment]
This is an emulator bug that has been fixed in the canary version of the emulator, but has not made it to the stable branch yet.  If you want to grab the fixed version of the emulator now:

1. In Android Studio, navigate to **Tools > SDK Manager > Appearance & Behavior > System Settings > Updates** and change to **Canary Channel**, and apply the changes.
2. Navigate to the **System Settings > Android SDK > SDK Tools** tab, and if the **Android Emulator** tool says "Update Available: 28.0.1" (or something newer), check the box and update it.
3. (Recommended) Go back to the Updates tab and change back to your previous channel.

See #148 for more info.
