### ISSUE TITLE
Displaying dynamic mesh in scene

### ISSUE THREAD

**Issue by evodabas** [google-ar/sceneform-android-sdk#284]
I'm trying to display an animated object in a scene where each frame of animation is an entirely new mesh. I'm continuously building up new RenderableDefinition instances (from individual vertex and index lists) and I want to be able to display the contents of each frame on a specific Node in the scene as the animation plays.

I've tried constructing a new ModelRenderable instance for each new frame and setting it on the target node with Node.setRenderable but this just causes the application to stutter and hang and generally stop working. I've also tried sticking with just one Renderable instance and repeatedly calling updateFromDefinition with the next frame's RenderableDefinition but this gives more or less the same result.

So I'm wondering if this is even a supported workflow? And if so what would be the recommended way to implement it?

Thanks,
Evan

**Comment by evodabas** [comment]
It seems the problems I was running into were actually user error (vertices being referenced beyond the supplied range). I'd still be interested in learning if there's are any official best practices though for working with dynamic geometry, and maybe other developer would be as well so I thought I'd leave this open until somebody from the sceneform team has a chance to reply.

**Comment by dsternfeld7** [comment]
Using updateFromDefinition is recommended for modifying an existing Renderable instead of creating a new one. This is because using updateFromDefinition internally allows memory to be re-used, so it is less expensive. However, memory has to be re-allocated if the number of vertices increases, in which case the performance benefit is lost. You can create more vertices than you initially need, and just not use them until you need them in your triangles list to re-gain some of that performance benefit.

That being said, updating geometry is still going to be an expensive thing to do, so if you are updating the geometry every frame, expect there to be a cost (especially if the geometry has many vertices).
