### ISSUE TITLE
How can I disable Face Culling using Sceneform and ModelRenderables?

### ISSUE THREAD

**Issue by ChronoAndross** [google-ar/sceneform-android-sdk#310]
Hello SceneForm team,

I am working with custom geometry (geometry coming out of another software), and using ModelRenderables to create my scene. Some of my faces are getting culled by the renderer. I realize this could be happening because the winding for some triangles are incorrect coming out of the other software, but this cannot be changed. However, I discovered an easier solution to this is to disable face culling within the renderer. However, it's hard for me to find where the rendering loop is located to place this.

Additionally, it seems that I can't find any options for the Sceneform API that allow for double-sided faces, particularly with junction with MaterialFactory. I already know about this: https://developers.google.com/ar/develop/java/sceneform/custom-material , and there is a doubleSided option there, but I believe this is primarily for working with .sfa files, and not ModelRenderables and MaterialFactory.

Please let me know if I'm missing anything here or if this is an issue for you to fix.

Thanks so much!

**Comment by romainguy** [comment]
You can disable face culling by creating a custom material. You can either use doubleSided or change culling to none.

**Comment by ChronoAndross** [comment]
Yes, but we aren't using the .sfa file format which seems the only way to utilize this at the moment. We are creating our geometry from ModelRenderables using custom geometry. The only material api I've seen through the ModelRenderables api is the MaterialFactory api, which does not allow for double sided triangles.

Is there a way for us to disable culling using the MaterialFactory api?

**Comment by kstpr** [comment]
Hi, I am from the same team. The problem is that we are trying to dynamically convert the raw meshes data from our custom file format to `ModelRenderables` and so we are using the `RenderableDefinition` API. Currently the workflow is as follows: we build a sampler with `Texture.Sampler.builder()`, then we build the texture with the `Texture.builder()` then we build the submeshes and finally we build the `RenderableDefinition`s. Thus we don't see a way to use the custom materials as we are not loading the models from static assets. Our iOS colleagues do similar thing with SceneKit and they are overcoming this problem with setting directly the doubleSided value using the SCNMaterial API (https://developer.apple.com/documentation/scenekit/scnmaterial/1462531-isdoublesided).

**Comment by ChronoAndross** [comment]
Is there any way to create the JSON string representing the custom material inside the .sfa and use that instead of writing out the .sfa at runtime? I feel uncomfortable writing materials to disk and then performing a read on those materials files at runtime.

**Comment by kstpr** [comment]
Thanks @romainguy, your suggestion worked. I had to pre-create two materials though - one with textures and one with plain color, as I couldn't find a way to reuse one in the two scenarions we experience. Then I set the appropriate texture or the color to a copy of the material I need.

**Comment by malik-at-work** [comment]
Currently the material is embedded into the sfb at build time.  For more questions on this let's open a new issue.

**Comment by michaelvogt** [comment]
@kstpr 
In cases like this, I create a parameter in the custom material, which is then used to decide what to render out in the fragment shader. That way you may be able to have the effect you describe with one material.
