### ISSUE TITLE
Shadows on an augmented image 

### ISSUE THREAD

**Issue by bobekos** [google-ar/sceneform-android-sdk#311]
Hi, 

it is possible to create a plane that receive shadows like the plane renderer but on detected augmented images? 
I tried to create a invisible plane on the image but it doesn't work. Any ideas? Thanks for help

**Comment by dsternfeld7** [comment]
The key to doing this is to create a custom material that uses the "shadowMultiplier" property that you can read about [here](https://developers.google.com/ar/develop/java/sceneform/custom-material).

The custom material would look something like this:

```
material {
    name : "Plane Shadow Material",
    shadingModel : unlit,
    blending : transparent,
    shadowMultiplier : true
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);

        material.baseColor = float4(0.0f, 0.0f, 0.0f, .6f);
    }
}
```

You could then create an .sfb for a quad/plane using this material. Then create a node using that renderable, and parent it to an anchor for the augmented image. You may also want to scale the node so that the size of the plane matches the augmented image.

**Comment by bobekos** [comment]
@dsternfeld7 

Oh man, i missed the "shadowMultiplier" property. Now it's working. It's look great. Thanks for you help.
