### ISSUE TITLE
Can I produce my own horizontal plane based on the anchor?

### ISSUE THREAD

**Issue by CranberryYam** [google-ar/sceneform-android-sdk#401]
I mean plane class.

**Comment by dsternfeld7** [comment]
Instead of using anchor's, you can look into using the [RenderableDefinition](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/RenderableDefinition) API to create a Renderable dynamically from the Plane's data which will need to be updated each time the plane is updated.

**Comment by CranberryYam** [comment]
> Instead of using anchor's, you can look into using the [RenderableDefinition](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/RenderableDefinition) API to create a Renderable dynamically from the Plane's data which will need to be updated each time the plane is updated.

Thanks!

**Comment by CranberryYam** [comment]
Can you give me more details about how to create a Renderable dynamically from the Plane's data?

**Comment by malik-at-work** [comment]
RenderableDefination will let you create a an arbitrary 3d shape.  Since this is an arbitrary 3D shape it's very flexible but is going to require some work to use.

A simpler option might be to make a cube with the [ShapeFactory.makeCube](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/ShapeFactory#makeCube(com.google.ar.sceneform.math.Vector3,%20com.google.ar.sceneform.math.Vector3,%20com.google.ar.sceneform.rendering.Material)) and scale it so that it's very thin.  There is some discussion of the shape factory here: https://developers.google.com/ar/develop/java/sceneform/create-renderables#create_simple_shapes_at_runtime
