### ISSUE TITLE
Why Textures gets swap between different Materials in OBJ ?

### ISSUE THREAD

**Issue by jagsrajput21** [google-ar/sceneform-android-sdk#50]
I am loading an OBJ Model in Sceneform. The Textures gets replaced between different materials. Why is this happening? 

Also, It is showing me following warning - 

WARNING: Material parameter types changed during conversion!  Run with --in_place (-i) to update your SFA.

**Comment by tpsiaki** [comment]
@jagsrajput21 - the warning you are seeing indicates that the SFA should be regenerated so that things like the parameters available in the material can better match the source asset.

A couple of things to check:

- Try deleting the SFA file, and building again (it will be regenerated).  If you made changes previously in the SFA, you might need to reapply these changes to the new SFA.
- Check your app's build.gradle file and make sure that each asset rule has a unique .sfa file name (i.e. make sure two of the aren't using the same SFA).

**Comment by jagsrajput21** [comment]
@tpsiaki I have done performed these things. Still, having the same issue.

**Comment by jagsrajput21** [comment]
@tpsiaki Any update on this?

**Comment by tpsiaki** [comment]
@jagsrajput21 - if possible, will you share out an example of an obj file (and mtl/png) where this occurs?

**Comment by tpsiaki** [comment]
@jagsrajput21 - thanks!  we will investigate what's going on here.

**Comment by tpsiaki** [comment]
This is fixed in the latest version of Sceneform - to get textures showing up correctly, upgrade to the 1.4.0 version of com.google.ar.sceneform:plugin, and either re-import the obj asset above, or if the asset is already included in your build.gradle files, delete the associated .sfa and .sfb files and rebuild.
