### ISSUE TITLE
how to display text above a transformable node using ontaplistner??

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#539]

**Comment by tpsiaki** [comment]
In order to display text above the node:

- Set up a [ViewRenderable node to be a child of your transformable node as in the Solar System sample](https://github.com/google-ar/sceneform-android-sdk/blob/2f8c877954e978ffd068d07a56fa08cc6ee8d208/samples/solarsystem/app/src/main/java/com/google/ar/sceneform/samples/solarsystem/Planet.java#L83)
- In your transformable node class, override BaseTransformableNode.onTap
- In your Node's onTap override, enable the ViewRenderable node [like the Solar System Sample](https://github.com/google-ar/sceneform-android-sdk/blob/2f8c877954e978ffd068d07a56fa08cc6ee8d208/samples/solarsystem/app/src/main/java/com/google/ar/sceneform/samples/solarsystem/Planet.java#L125)
