### ISSUE TITLE
Importing sceneform animation 1.7.0 sigsegv error

### ISSUE THREAD

**Issue by acguterres** [google-ar/sceneform-android-sdk#544]
After importing sceneform animation 1.7.0 to my app's build gradle, I get a sigsegv fault error when trying to run my app.
<img width="600" alt="screen shot 2019-02-19 at 1 44 41 pm" src="https://user-images.githubusercontent.com/46457142/53049727-8c72bf80-344c-11e9-92c7-84a797541b3f.png">
When I take out the animation code, the app runs fine and am able to view models but w/ out the skeletal animation. I tried running the sample animation app from the examples, but I get the same error when trying to run an animation. I'm using an android emulator to run the virtual scene.

**Comment by hvardhan617** [comment]
Facing the same issue..Anybody who got the animation sample running on the emulator?

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- Android Studio version
- Sceneform version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell pm path com.google.ar.core`
- Output of `adb shell getprop ro.build.fingerprint`
- Specific error message or problem encountered
