### ISSUE TITLE
Placing an object on previously created anchor on Tap

### ISSUE THREAD

**Issue by ishant1044** [google-ar/sceneform-android-sdk#558]
I am trying to place an object on a previously created anchor on tap. 

1. Let's say I have already placed one anchor 'A' on the surface.

2. Next time, when the user is tapping on the surface, I am trying to place one new object on the same anchor on the tapped place.
`
 fragment.setOnTapArPlaneListener(
                (HitResult hitResult, Plane plane, MotionEvent motionEvent) -> {
....
....
`

This returns one HitResult object. I have tried to calculate the distance between the origin of the Anchor 'A' and the tapped area by subtracting the values of Pose x,y,z between them.

But it places the object on a different location, not where the user has tapped.

Could you please help me on it.

**Comment by dsternfeld7** [comment]
Can you please share more of your code?

If you set the parent of the new object to the AnchorNode first, and then call setWorldPosition and setWorldRotation with the pose from the new hitResult object, then that will automatically convert the world position to a local position relative to it's parent (the Anchornode).

I suspect the reason that your code isn't working is because rotation isn't being accounted for when you calculate the local position. If you would still like to calculate the local pose yourself, you can use anchorNode.worldToLocalPoint to calculate the local position. To calculate the local rotation, do this:

`Quaternion localRotation = Quaternion.multiply(anchorNode.getWorldRotation().inverted(), worldRotation));`

**Comment by ishant1044** [comment]
Thank you for the reply.

Problem Statement : We are creating one new anchor using Augmented image. The node object is placed whenever user is tapping on the screen.

Issue : The node is placed on different location each time, not exactly where the user has tapped. Even if we tapped on the same location, it is placed on different location.
`
fragment.setOnTapArPlaneListener(
                (HitResult hitResult, Plane plane, MotionEvent motionEvent) -> {
                  
                            placeObject(hitResult,fragment, Uri.parse(objTypeFile));

                        }
                    }
                }
        );
`
inside placeObject, we are creating one ar object and adding the node like below :
`
 node.setWorldPosition(new Vector3(hitResult.tx(),hitResult.ty(),hitResult.tz());

//create one anchor on augmented image detected
Anchor imgAnchor = anchorAugmentedImage.createAnchor(anchorAugmentedImage.getCenterPose());
//create one anchor node using above anchor
  AnchorNode anchorNode = new AnchorNode(imgAnchor);
//set the parent of the anchornode
  anchorNode.setParent(fragment.getArSceneView().getScene());
  node.setParent(anchorNode);
`

**Comment by ishaang10** [comment]
Try using a AnchorNode previousAnchornode in your code for storing the previous anchor. so if you make a model set parent to previousAnchorNode
