### ISSUE TITLE
How can i delete anchornode and/or nodes from a scene using a button?

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#579]

**Comment by tpsiaki** [comment]
In order to do this you'll need to:

1. Create A Button - this can be done using a ViewRenderable that has an Android Button on it.  An example of this being done is creation of a ViewRenderable in [Solar System SolarActivity initialization](https://github.com/google-ar/sceneform-android-sdk/blob/2f8c877954e978ffd068d07a56fa08cc6ee8d208/samples/solarsystem/app/src/main/java/com/google/ar/sceneform/samples/solarsystem/SolarActivity.java#L121).
2. Place the Button in the scene - this is done by adding the ViewRenderable to a Node in the scene.  This is done in the Solar System sample in [SolarActivity during Solar System creation](https://github.com/google-ar/sceneform-android-sdk/blob/2f8c877954e978ffd068d07a56fa08cc6ee8d208/samples/solarsystem/app/src/main/java/com/google/ar/sceneform/samples/solarsystem/SolarActivity.java#L365), but can be done at any time (e.g. at creation, or in response to user input) in your app.
3. Get the [Android View from the ViewRenderable](https://github.com/google-ar/sceneform-android-sdk/blob/2f8c877954e978ffd068d07a56fa08cc6ee8d208/samples/solarsystem/app/src/main/java/com/google/ar/sceneform/samples/solarsystem/SolarActivity.java#L368), and use Android view functionality like findViewById to get the button you'd like to respond to.  Add an on click listener to this button.
4.  In the onClick listener, call [Node.setParent(null)](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/Node#setParent(com.google.ar.sceneform.NodeParent)) on the Node you wish to remove, in order to remove it from the Scene.

**Comment by ishaang10** [comment]
@tpsiaki  imagine i haveultiple nodes in the scene.so i want to tap a node and delete that particular node from the scene.. how can i do that? or maybe a particular anchor but selecting it by tapping it

**Comment by bobekos** [comment]
Check:
Node.setOnTapListener

I mean all you need is already implemented in the samples. Please check the
examples.

ishaang10 <notifications@github.com> schrieb am Fr., 8. März 2019, 17:20:

**Comment by ishaang10** [comment]
finaly solved my own issue using this....

Button button=findViewById(R.id.button);
                    model.setOnTapListener((hitTestResult, motionEvent1) -> button.setOnClickListener(v -> model.setParent(null)));

**Comment by mmoussa** [comment]
@ishaang10 I tried your solution but it requires tapping the node once before you can close it with the button. Is it the same for you?
