### ISSUE TITLE
getAnimationDataCount always returns 1

### ISSUE THREAD

**Issue by wwdablu** [google-ar/sceneform-android-sdk#598]
I have push the code changes here in (https://github.com/wwdablu/SceneformAnimate/tree/dev) but whenever I am calling the get method it always returns 1, even though in the SFA/SFB I can see that the animation array defined as two values.

When I call modelRenderable.getAnimationData(0), then it returns a valid anim data. I am not sure as to what wrong am I doing as because in the same app it works good.

I have taken the models from Mixamo. Each FBX has the animation as well as the skin data.

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- Android Studio version
- Sceneform version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell pm path com.google.ar.core`
- Output of `adb shell getprop ro.build.fingerprint`
- Specific error message or problem encountered

**Comment by wwdablu** [comment]
Providing the information as requested as the issue is still reproducible.

- Android Studio version
Version 3.3.1 (Mac OS X)
- Sceneform version
1.7.0
- Device manufacturer, model, and O/S
Google, Pixel 2, Android Pie (April patch installed)
- ARCore APK installed version:
1.8.190311106
- On Windows, use: adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"
N/A
- On macOS, use: adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:
- Output of adb shell pm path com.google.ar.core
- Output of adb shell getprop ro.build.fingerprint
- Specific error message or problem encountered
No error message is displayed. Only the method getAnimationDataCount always returns 1.

The code which is being used to testing is shared in GitHub (https://github.com/wwdablu/SceneformAnimate/tree/dev).

**Comment by Stefjs** [comment]
Same problem here...
