### ISSUE TITLE
Amount of memory used

### ISSUE THREAD

**Issue by PaulTVungle** [google-ar/sceneform-android-sdk#60]
We are profiling our ARCore/Sceneform app on a Pixel 2, up to date with everything as of today.  At first glance it seems that a lot of memory is allocated when the ArFragment gets going and starts to look for planes.  The total reported by dumpsys meminfo and the profiler is 350MB or so.

This is before setting an anchor and adding scene nodes.  When we add a little over 130,000 triangles (I know it is too many, but we are losing the battle with the designers at the moment), this total memory figure rises to nearly 500MB.  Performance is still quite reasonable, though.

The main components as reported by the profiler seem to be:

    Heap 54MB
    Native 140MB
    Graphics 275MB

With a 512MB Java heap limit, that's not going to be a problem.  My question is, when would native and graphics memory consumption become an issue?  Is this memory almost free, depending on available physical RAM, or will the runtime kill our app if it uses too much of either?

Appreciate that memory may be reported before it is actually committed, so I am taking the figures with a pinch of salt, but if you could give approximate guidance on the size of native and graphics memory segments then that would be very helpful.

**Comment by malik-at-work** [comment]
This doc is good starting point:  https://developer.android.com/topic/performance/memory

The answers are going to be very device dependent, but most mobile devices graphics memory is unified so there should not be extra limits on graphics memory vs memory used for other purposes. Same for native memory.

I don't think simple numerical limits work here, because it depends on what phones you are targeting, what else is happening on that phone, as well as how your app uses the memory.

**Comment by PaulTVungle** [comment]
Thanks very much for that, @malik-at-work.  Sounds like we will only find out by testing on a variety of devices.

Maybe a word could be had with the people at the Firebase Test Lab to see if it would be possible to target only AR Core/Sceneform-supported handsets in a test run?

**Comment by romainguy** [comment]
The Graphics and Native heaps won't count against your Java heap limit (only bitmaps used to load textures will).

**Comment by PaulTVungle** [comment]
That's great.  We have acquired a Moto G6+ now as a "mid-range" test device and the performance is pretty nice even on our unoptimised scene.

**Comment by romainguy** [comment]
Sceneform's renderer prioritizes framerate over quality. What happens when your scene is unoptimized is that the renderer will drop the resolution dynamically (changes can happen on every frame). This is done in a smooth manner so as the effect remains invisible to most (if not all) users, but optimizing your scene is a good way to keep your resolution high :)
