### ISSUE TITLE
ARCore Sceneform 1.7 Import FBX assets issue

### ISSUE THREAD

**Issue by YinXiuYu** [google-ar/sceneform-android-sdk#600]
ARCore Sceneform 1.7 import FBX assets , the final model partial display dislocation issue.
Here is the xgirl.fbx assets, Can you compare and tell me the key reason? 
Thanks  a lot for your great support in advance!

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- Android Studio version
- Sceneform version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell pm path com.google.ar.core`
- Output of `adb shell getprop ro.build.fingerprint`
- Specific error message or problem encountered
