### ISSUE TITLE
import fbx asset bug 

### ISSUE THREAD

**Issue by 544531645** [google-ar/sceneform-android-sdk#601]
I use my fbx file , before in virocore is work ,but when use sceneform import say create sfa error , this my file . can you help me ?
[apple.zip](https://github.com/google-ar/sceneform-android-sdk/files/2970130/apple.zip)

**Comment by 544531645** [comment]
@tpsiaki

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- Android Studio version
- Sceneform version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell pm path com.google.ar.core`
- Output of `adb shell getprop ro.build.fingerprint`
- Specific error message or problem encountered
