### ISSUE TITLE
Rendering object at specific react angle or bounding box.

### ISSUE THREAD

**Issue by Aniketrajput039** [google-ar/sceneform-android-sdk#611]
I want to put my object in a bounding box that is taken at run time.

**Comment by tpsiaki** [comment]
If you have a bounding box in which you'd like your model to fit, the best way to achieve this is to get the collision shape from the ModelRenderble using [getCollisionShape](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/rendering/Renderable#getCollisionShape()).

Next you should be able to cast this to a [Box](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/collision/Box) and find the model size from the bounds of the box.

Finally, adjust the scale of the model accordingly so that the collision box fits in the bounding box you are targetting.

**Comment by fredsa** [comment]
For advice and general questions, please use the `Sceneform` tag on
Stack Overflow: https://stackoverflow.com/questions/tagged/Sceneform

In addition, please see the Sceneform SDK [developer documentation](https://developers.google.com/ar/develop/java/sceneform/) and [API reference](https://developers.google.com/ar/reference/java/sceneform/reference/packages).
