### ISSUE TITLE
Can anyone tell me how to add a 2 points measure (ruler) function in my app

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#619]

**Comment by ManuelTS** [comment]
You clearly don't know the difference between Github and Stackoverflow. The latter is for your question.

**Comment by ishaang10** [comment]
arcore community at stackoverflow is not so active and very small. i use that too but dont get any response . not even views

**Comment by ManuelTS** [comment]
A polite more elaborated clarification:

Github **issues** is for reporting issues, asking if something is a bug, or issuing feature requests. Stackoverflow is for asking general programming and implementation questions and problems related to your question, in a how-to-do fashion, but not for issue reporting.

You want to build an two point ruler with Sceneform and you are asking "Can anyone tell me how to add a 2 points measure (ruler) function in my app"? Consequentially, you should at least not ask on github issues if anyone knows how to implement a 2 point ruler, since github issues as its name states, is for issues about the technology itself, and not what you want do do with it.

It is indifferent how active a community is, if the system (github issues) is not intended for your matter.
