### ISSUE TITLE
[Feature Request] modified scaling using scalecontroller according to particular axis

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#623]

**Comment by tpsiaki** [comment]
The easiest way to get this behavior would be to create your own version of the scalecontroller which is open sourced here: https://github.com/google-ar/sceneform-android-sdk/blob/master/sceneformux/ux/src/main/java/com/google/ar/sceneform/ux/ScaleController.java#L98

In order to scale just one dimension, modify this line to only set the finalScaleValue to the axes you wish to modify, and set the axes that you wish to remain constant at a constant value (e.g. 1.0): https://github.com/google-ar/sceneform-android-sdk/blob/2f8c877954e978ffd068d07a56fa08cc6ee8d208/sceneformux/ux/src/main/java/com/google/ar/sceneform/ux/ScaleController.java#L97

**Comment by MrCsabaToth** [comment]
My problem is that `PinchGesture` only supplies `float`. How can I get `Vector3` deltas from `PinchGesture`?
