### ISSUE TITLE
Chromakey video sample invert effect

### ISSUE THREAD

**Issue by BenjaminFaal** [google-ar/sceneform-android-sdk#631]
In https://github.com/google-ar/sceneform-android-sdk/blob/master/samples/chromakeyvideo/app/sampledata/models/chroma_key_video_material.mat

It removes the green color from the video, how to reverse the effect to keep specified colors in the video and remove all other colors?

**Comment by tpsiaki** [comment]
The chromakey video sample simply sets the alpha based on the green color.  In order to negate the behavior in the material that you linked, instead of setting alpha to `smoothstep(edge0, threshold, distance)` like that sample does, set it to `1.0 - smoothstep(edge0, threshold, distance)` and you should see the opposite behavior.
