### ISSUE TITLE
Adding an object on vertical plane always rotated.

### ISSUE THREAD

**Issue by jagsrajput21** [google-ar/sceneform-android-sdk#65]
I am adding a TV Model on a vertical plane. TV is always rotated in the y-axis.

![screenshot_20180604-122250](https://user-images.githubusercontent.com/6915256/40902769-cb94a38a-67f2-11e8-8c59-ea09965ef62c.png)

It should be parallel to the horizontal plane.

My code for placing TV object on vertical Plane is -

AnchorNode anchorNode = new AnchorNode(hit.createAnchor());
TransformableNode node = new TransformableNode(fragment.getTransformationSystem());
node.setRenderable(renderable);
node.setParent(anchorNode);
fragment.getArSceneView().getScene().addChild(anchorNode);

**Comment by malik-at-work** [comment]
The Transformation System was designed for horizontal user experiences. We worked closely with our UX designers and researchers to design it in Sceneform 1.0.  

Our upcoming release will address vertical experiences.

In the meantime I might suggest inserting a node to add a rotation.

**Comment by jagsrajput21** [comment]
@malik-at-work How inserting a node to add a rotation will solve this problem? Can you please elaborate?

**Comment by khonakr** [comment]
+1
@malik-at-work I would like to know how to change axis of rotation using a node as well. 
My models are on horizontal surface but they rotate in an incorrect axis and would like to know a work around.

**Comment by dsternfeld7** [comment]
When the anchor is created, that anchor includes a rotation where the up direction of the node is along the surface normal of the plane, and also faces roughly towards the user's device. A more detailed description of this is [here](https://developers.google.com/ar/reference/java/com/google/ar/core/HitResult.html#getHitPose()).

After setting parent of the TV node to the anchor, you can change the TV nodes rotation so that it is always facing in the correct direction you want:

```
if (plane.getType() == Type.VERTICAL) {
            Vector3 anchorUp = anchorNode.getUp();
            andy.setLookDirection(Vector3.up(), anchorUp);
}
```

@khonakr I believe the question you are asking is slightly different. The axis of rotation for a TransformableNode is always the up direction of the anchor (aka the surface normal of the plane). You may want to do the following:

1. Create a new Node and set its parent to the TransformableNode.
2. Set the Renderable on the new node, not the transformable node itself.
3. Rotate the new node by 90 degrees.

This way, the TransformableNode is still rotated along the surface normal of the plane, but the rendered object is rotated relative to that. One important note is that the TransformableNode still needs its own collision shape so that the node can be selected and dragged (which by default comes from the Renderable).

There is an example [here](https://github.com/dsternfeld7/sceneform_raise_transformation_example/commit/bfe582401ba39cd07ed85c334445eb64cf9744ef#diff-bdb8ebc17af33d2e28225149392ff54f) that does something similar that will help show you how to add a child to the TransformableNode and setup the collision shapes correctly.

**Comment by khurramengr** [comment]
@jagsrajput21 did you manage to solve this issue?

**Comment by SarvagyaVaish** [comment]
```
            Vector3 anchorUp = anchorNode.getUp();
            andy.setLookDirection(Vector3.up(), anchorUp);
```
^^ this fixed the issue for me :) 

Also, thank you @dsternfeld7 for the link describing the coordinate system setup for anchors based on plane type.
