### ISSUE TITLE
node.localPosition() affects scaling of attached ViewRenderable 

### ISSUE THREAD

**Issue by valentinrueeck** [google-ar/sceneform-android-sdk#72]
Hi, I'm playing around with augmented images. When an image is detected, I attach an `AnchorNode` to the anchor created on the image. This `AnchorNode` is the parent of a `Node` which has a `ViewRenderable` attached. When I set the `Node`'s local position it affects the size of the `ViewRenderable`. So the smaller the `y` - value of the `localPosition `vector gets, the smaller is the `ViewRederable`.

```
CompletableFuture<ViewRenderable> future = ViewRenderable.builder().setView(context, R.layout.text_view).build();
        future.thenAccept( view -> {
            int height = Math.round(view.getPixelsToMetersRatio() * 0.25f);
            int width = Math.round(view.getPixelsToMetersRatio() * image.getExtentX());

            TextView headline = view.getView().findViewById(R.id.textViewHeadline);
            SpannableString headlineText = new SpannableString(image.getName());
            headlineText.setSpan(new UnderlineSpan(),0, headlineText.length(),0);
            headline.setText(headlineText);

            TextView descriptionText = view.getView().findViewById(R.id.textView);
            descriptionText.setText(PaintingDescriptionTextRetriever.retrieveDescriptionText(image.getName()));
            descriptionText.setWidth(width);
            descriptionText.setHeight(height);

            Node descriptionPlaneNode = new Node();
            descriptionPlaneNode.setName("descriptionPlaneNode");
            descriptionPlaneNode.setRenderable(view);
            descriptionPlaneNode.setParent(anchorNode);
            descriptionPlaneNode.setLocalRotation(new Quaternion(new Vector3(1,0,0), -90));
            descriptionPlaneNode.setLocalPosition(new Vector3(0f,-image.getExtentZ() - 1.5f,0f));
        });
```

**Comment by dsternfeld7** [comment]
Thanks for the report! Can you include some screenshots that show the issue?

**Comment by valentinrueeck** [comment]
`descriptionPlaneNode.setLocalPosition(new Vector3(0f,-image.getExtentZ() - 1f ,0f));`
![screenshot_20180606-124724_arcore_ir](https://user-images.githubusercontent.com/22748174/41033833-1f4ca86a-6988-11e8-8084-c05f30ff7f3f.jpg)

descriptionPlaneNode.setLocalPosition(new Vector3(0f,-image.getExtentZ() ,0f));
![screenshot_20180606-124806_arcore_ir](https://user-images.githubusercontent.com/22748174/41033914-565745b8-6988-11e8-8995-d5d78f94de1d.jpg)

**Comment by malik-at-work** [comment]
It looks like your Anchor is at the center pose of the augmented image. Anchors are defined so that “up/ the positive y axis” is perpendicular to the surface the Anchor is placed on. 

This code changes the Y position of the Node by subtracting one. After applying the Anchor’s rotation, subtracting one in Y will move the node farther away from the camera. Views and the text within them are affected by distance to the camera and will appear smaller or larger if they are closer / farther away. If you move the node along the X or Z axis instead, it should move parallel to the augmented image instead.

This means that the AR position of the Node is actually farther away than the Starry Night image. Currently AR objects are always shown on top of the camera, which breaks the illusion of AR here since the object should be hidden by the object in the real world.

The rotation applied by the Anchor is also why you needed rotate the Node by 90 degrees to make it face in the same direction as the image.

**Comment by valentinrueeck** [comment]
You're right. I had already tried to change the rotation, but I have forgotten about the anchor's rotation....
