### ISSUE TITLE
creating dummy plane and hit test on that. and move my model in that plane

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#774]
i have  a model getting placed on the ground plane.. i move the y axis and movethe model to the ceiling. now i want to create a dummy plane at the height of the model and using hittest/ray move the fan on that plane. how can i do so?

**Comment by tonilsz** [comment]
I've been testing for something similar, I've made all work except the translation of the object.

The problem is that if you try to extend or copy 'TranslationController' you will see that "frame.hitTest(x, y)" only can return 'Trackable' objects, and there is no way to create a Trackable. I'm stuck on this, and at the moment I'm still using the detected planes from Arcore. 

One possible solution can be, to make a mix from translationController to the event OnClick of your created plane, but it requires a lot of work.

**Comment by ishaang10** [comment]
can you tell mw how did you mke a dummy plane?

**Comment by tonilsz** [comment]
I made it with ShapeFactory.makeCube and making it flat

**Comment by ishaang10** [comment]
Is there a way to create a node/anchornode or transformable node on an object?? 

like creating an anchornode on your flat cube?
