### ISSUE TITLE
Android Studio 3.5  SceneForm Plugin not working

### ISSUE THREAD

**Issue by MehmoodArib** [google-ar/sceneform-android-sdk#841]
i am building  both app and project gradle with "1.11.0".
and using the plugin 1.11.1 and tried plugin 1.11.0 too. still i am unable to run.
my android studio version is 3.5
i can see the viewer but it's blank. on opening sfa or sfb i am only seeing the plain text. please help

_Originally posted by @MehmoodArib in https://github.com/google-ar/sceneform-android-sdk/issues/815#issuecomment-526132083_

**Comment by tpsiaki** [comment]
Hi Mehmood - the 1.11.1 fix only corrected a crash on Windows & Linux on all versions of Android Studio, whereas there's a different issue that #815 is tracking regarding compatibility with Android Studio 3.5, which as far as I am aware repros on all platforms, and with all versions of the Sceneform Android Studio plugin.

We have the fix for that and it will be available in the next Sceneform plugin release.  In the interim the only way to use the previewer is to install an earlier version of Android Studio.

**Comment by MehmoodArib** [comment]
okay thanks for the support.
