### ISSUE TITLE
Drawing app in sceneform

### ISSUE THREAD

**Issue by phoenixxt** [google-ar/sceneform-android-sdk#89]
Right now I use small spheres created by Material and Shape factories for drawing and it works okay, but after creating a hundred different lines and that means thousands of spheres the app starts to lag a little (samsung s8 plus). Is there maybe a better way that sceneform provides to enable drawing in space?

**Comment by claywilkinson** [comment]
The main use case for Sceneform we're targeting is rendering 3D models in AR with the presumption these models are created by modeling tools and then imported into the application.

Building these models dynamically is possible. As you noticed, the performance will drop when you get a lot of objects in the scene.  You might want to look into the procedural geometry API  in [RenderableDefinitionBuilder](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/RenderableDefinition.Builder) and build the geometry dynamically.  This will reduce the number of draw calls made since you are adding vertices to 1 model (or a few models) vs. an entire model.

Unfortunately I don't know of a sample that does this (yet), but if you get something working, I'd love to see it!

**Comment by malik-at-work** [comment]
@phoenixxt  There is a sample posted which creates geometry dynamically to draw a line.  You can download the sample repository from https://github.com/googlesamples/sceneform-samples and try the drawing app. 

 
The sample code you are looking for is at https://github.com/googlesamples/sceneform-samples/blob/master/drawing/app/src/main/java/com/google/ar/sceneform/samples/drawing/ExtrudedCylinder.java which creates a cylinder shaped segments and joins them along list of points.
